services:
  papermc:
    image: papermc
    environment:
      - MIN_RAM=${MIN_RAM}
      - MAX_RAM=${MAX_RAM}
    build:
      context: .
      args:
        - MC_VERSION=${MC_VERSION}
        - UNAME=${UNAME}
        - UID=${UID}
        - GID=${GID}
    container_name: mc-server
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 25565:25565
    volumes:
      - ./world:/minecraft/world
      - ./world_nether:/minecraft/world_nether
      - ./world_the_end:/minecraft/world_the_end
      - ./plugins:/minecraft/plugins
      - type: bind
        source: ./config/bukkit.yml
        target: /minecraft/bukkit.yml
      - type: bind
        source: ./config/server.properties
        target: /minecraft/server.properties
      - type: bind
        source: ./config/spigot.yml
        target: /minecraft/spigot.yml
      - type: bind
        source: ./config/whitelist.json
        target: /minecraft/whitelist.json
      - type: bind
        source: ./config/ops.json
        target: /minecraft/ops.json
      - type: bind
        source: ./config/banned-ips.json
        target: /minecraft/banned-ips.json
      - type: bind
        source: ./config/banned-players.json
        target: /minecraft/banned-players.json

volumes:
  world:
    driver: local
  world_nether:
    driver: local
  world_the_end:
    driver: local
  plugins:
    driver: local