services:
  papermc:
    image: papermc
    build:
      context: .
      args:
        MC_VERSION: 1.21.3
        MIN_RAM: 1G
        MAX_RAM: 8G
    container_name: mc-server
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 25565:25565
    volumes:
      - ./world:/minecraft/world
      - ./world_nether:/minecraft/world_nether
      - ./world_the_end:/minecraft/world_the_end
      - type: bind
        source: ./config/bukkit.yml
        target: /minecraft/bukkit.yml
      - type: bind
        source: ./config/server.properties
        target: /minecraft/server.properties
      - type: bind
        source: ./config/spigot.yml
        target: /minecraft/spigot.yml
      - type: bind
        source: ./config/whitelist.json
        target: /minecraft/whitelist.json
      - ./plugins:/minecraft/plugins

volumes:
  world:
    driver: local
  world_nether:
    driver: local
  world_the_end:
    driver: local
  plugins:
    driver: local