services:
  papermc:
    image: papermc
    build:
      context: .
      args:
        MC_VERSION: 1.21.3
        MIN_RAM: 1G
        MAX_RAM: 8G
    container_name: mc-server
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 25565:25565
    volumes:
      - ./world:/minecraft/world
      - ./plugins:/minecraft/plugins

volumes:
  world:
    driver: local
  plugins:
    driver: local